name: Deploy Hugo

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Importante se o tema é um submódulo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true  # Se você usa a versão Extended do Hugo

      - name: Build
        run: |
          hugo --minify
          touch ./public/.nojekyll  # Cria o arquivo para desativar o Jekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Diretório de publicação alterado para "public"
          publish_branch: gh-pages  # Branch para onde o GitHub Pages deve apontar
